[package]
name = "plustwo-database"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "1.1.7", features = [
	"sqlx-postgres",
	"runtime-tokio",
	"macros",
	"with-chrono",
	"with-uuid",
] }

[lints]
workspace = true
