//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "broadcasters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub display_name: String,
    pub profile_image_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::broadcasts::Entity")]
    Broadcasts,
}

impl Related<super::broadcasts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Broadcasts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
