//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "message_kind")]
pub enum MessageKind {
    #[sea_orm(string_value = "plus_two")]
    PlusTwo,
    #[sea_orm(string_value = "minus_two")]
    MinusTwo,
}
